# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-03 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('is_right', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Стандартный ответ',
                'verbose_name_plural': 'Стандартные ответы',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='AnswerFree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
            ],
            options={
                'verbose_name': 'Свобоный ответ',
                'verbose_name_plural': 'Свободные ответы',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Язык программирования')),
            ],
            options={
                'verbose_name': 'Язык программирования',
                'verbose_name_plural': 'Языки программирования',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('type', models.CharField(choices=[('standard', 'standard'), ('free', 'free')], max_length=20, verbose_name='Тип вопроса')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.Language')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text', models.TextField(blank=True, null=True, verbose_name='свободный текст')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.Question')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test.Answer')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.Test')),
            ],
            options={
                'verbose_name': 'Тестовое задание',
                'verbose_name_plural': 'Тестовые задания',
                'ordering': ['test'],
            },
        ),
        migrations.AddField(
            model_name='answerfree',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.Question'),
        ),
    ]
